"""create table birds

Revision ID: 279655b0cf5d
Revises: 
Create Date: 2023-05-31 10:03:50.578359

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '279655b0cf5d'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('birds',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=True),
    sa.Column('species', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('birds')
    # ### end Alembic commands ###
